<?php
/** INICIO MENSAJES DEL SISTEMA */
$MESSAGE_ADD =                          "<div class='bottom-0 start-50 translate-middle-x toast mb-2 w-50' data-autohide='true'><div class='toast-header bg-success' style='font-size: 20px;'><span class='mr-auto text-white'><i class='las la-check-square'></i>&nbsp;&nbsp;¡Correcto!</span></div><div class='toast-body bg-success-10 text-success text-center' style='font-size: 28px;'>Registro guardado correctamente</div></div>";
$MESSAGE_ERROR =                        "<div class='bottom-0 start-50 translate-middle-x toast mb-2 w-50' data-autohide='true'><div class='toast-header bg-danger' style='font-size: 20px;'><span class='mr-auto text-white'><i class='las la-window-close'></i>&nbsp;&nbsp;¡Error!</span></div><div class='toast-body bg-danger-10 text-danger text-center' style='font-size: 28px;'>No fue posible guardar el registro</div></div>";
$MESSAGE_EXIST =                        "<div class='bottom-0 start-50 translate-middle-x toast mb-2 w-50' data-autohide='true'><div class='toast-header bg-warning' style='font-size: 20px;'><span class='mr-auto text-white'><i class='las la-exclamation-triangle'></i>&nbsp;&nbsp;¡Error!</span></div><div class='toast-body bg-warning-10 text-warning text-center' style='font-size: 28px;'>El registro que intenta agregar ya existe</div></div>";
$MESSAGE_FINISH =                       "<div class='bottom-0 start-50 translate-middle-x toast mb-2 w-50' data-autohide='true'><div class='toast-header bg-warning' style='font-size: 20px;'><span class='mr-auto text-white'><i class='las la-exclamation-triangle'></i>&nbsp;&nbsp;¡Alerta!</span></div><div class='toast-body bg-warning-10 text-warning text-center' style='font-size: 28px;'>Todas las Unidades han sido captados o no existen Unidades registradas</div></div>";
$MESSAGE_ERROR_RANGO_DIA =              "<div class='bottom-0 start-50 translate-middle-x toast mb-2 w-50' data-autohide='true'><div class='toast-header bg-danger' style='font-size: 20px;'><span class='mr-auto text-white'><i class='las la-exclamation-triangle'></i>&nbsp;&nbsp;¡Alerta!</span></div><div class='toast-body bg-danger-10 text-danger text-center' style='font-size: 28px;'>La Fecha Inicial no puede ser mayor que la Fecha Final</div></div>";
$MESSAGE_ERROR_DIFERENTE_DIA =          "<div class='bottom-0 start-50 translate-middle-x toast mb-2 w-50' data-autohide='true'><div class='toast-header bg-danger' style='font-size: 20px;'><span class='mr-auto text-white'><i class='las la-exclamation-triangle'></i>&nbsp;&nbsp;¡Alerta!</span></div><div class='toast-body bg-danger-10 text-danger text-center' style='font-size: 28px;'>La Fecha Inicial tiene que ser igual a la Fecha Final</div></div>";
$MESSAGE_ERROR_RANGO_MES =              "<div class='bottom-0 start-50 translate-middle-x toast mb-2 w-50' data-autohide='true'><div class='toast-header bg-danger' style='font-size: 20px;'><span class='mr-auto text-white'><i class='las la-exclamation-triangle'></i>&nbsp;&nbsp;¡Alerta!</span></div><div class='toast-body bg-danger-10 text-danger text-center' style='font-size: 28px;'>El Mes Inicial no puede ser diferente al Mes Final</div></div>";
$MESSAGE_ERROR_RANGO_ANO =              "<div class='bottom-0 start-50 translate-middle-x toast mb-2 w-50' data-autohide='true'><div class='toast-header bg-danger' style='font-size: 20px;'><span class='mr-auto text-white'><i class='las la-exclamation-triangle'></i>&nbsp;&nbsp;¡Alerta!</span></div><div class='toast-body bg-danger-10 text-danger text-center' style='font-size: 28px;'>El Año Inicial no puede ser diferente al Año Final</div></div>";
$MESSAGE_ERROR_ARCHIVO_NO_DISPONIBLE =  "<div class='bottom-0 start-50 translate-middle-x toast mb-2 w-50' data-autohide='true'><div class='toast-header bg-danger' style='font-size: 20px;'><span class='mr-auto text-white'><i class='las la-exclamation-triangle'></i>&nbsp;&nbsp;¡Alerta!</span></div><div class='toast-body bg-danger-10 text-danger text-center' style='font-size: 28px;'>El archivo no ha sido generado</div></div>";
$MESSAGE_RANGO_FACTURAS =               "<div class='bottom-0 start-50 translate-middle-x toast mb-2 w-50' data-autohide='true'><div class='toast-header bg-danger' style='font-size: 20px;'><span class='mr-auto text-white'><i class='las la-window-close'></i>&nbsp;&nbsp;¡Error!</span></div><div class='toast-body bg-danger-10 text-danger text-center' style='font-size: 28px;'>Verifique los n&uacute;meros de factura<br>Factura Inicial no puede ser mayor o igual a Factura Final</div></div>";
$MESSAGE_RANGO_ENTREGA_FACTURAS =       "<div class='bottom-0 start-50 translate-middle-x toast mb-2 w-50' data-autohide='true'><div class='toast-header bg-danger' style='font-size: 20px;'><span class='mr-auto text-white'><i class='las la-window-close'></i>&nbsp;&nbsp;¡Error!</span></div><div class='toast-body bg-danger-10 text-danger text-center' style='font-size: 28px;'>Error en rango de Facturas definido<br>Factura Inicial no puede ser menor a Factura Final</div></div>";
$MENSAJE_VALIDAR_FACTURAS_COMERCIAL =   "<div class='bottom-0 start-50 translate-middle-x toast mb-2 w-50' data-autohide='true'><div class='toast-header bg-danger' style='font-size: 20px;'><span class='mr-auto text-white'><i class='las la-exclamation-triangle'></i>&nbsp;&nbsp;¡Atenci&oacute;n!</span></div><div class='toast-body bg-danger-10 text-danger text-center' style='font-size: 28px;'>Para cerrar el d&iacute;a tienes que validar las facturas captadas</div></div>";
$MENSAJE_VALIDACION_INCORRECTA =        "<div class='bottom-0 start-50 translate-middle-x toast mb-2 w-50' data-autohide='true'><div class='toast-header bg-danger' style='font-size: 20px;'><span class='mr-auto text-white'><i class='las la-exclamation-triangle'></i>&nbsp;&nbsp;¡Atenci&oacute;n!</span></div><div class='toast-body bg-danger-10 text-danger text-center' style='font-size: 28px;'>Los datos introducidos no coinciden con los datos guardados</div></div>";
$MENSAJE_VALIDACION_CORRECTA =          "<div class='bottom-0 start-50 translate-middle-x toast mb-2 w-50' data-autohide='true'><div class='toast-header bg-success' style='font-size: 20px;'><span class='mr-auto text-white'><i class='las la-exclamation-triangle'></i>&nbsp;&nbsp;¡Correcto!</span></div><div class='toast-body bg-success-10 text-success text-center' style='font-size: 28px;'>La Factura ha sido validada correctamente</div></div>";
$MENSAJE_SIN_REGISTROS =                "<div class='bottom-0 start-50 translate-middle-x toast mb-2 w-50' data-autohide='true'><div class='toast-header bg-warning' style='font-size: 20px;'><span class='mr-auto text-white'><i class='las la-exclamation-triangle'></i>&nbsp;&nbsp;¡Error!</span></div><div class='toast-body bg-warning-10 text-warning text-center' style='font-size: 28px;'>No existen registros en la fecha seleccionada.</div></div>";
$MESSAGE_TOKEN_ADD =                    "<div class='bottom-0 start-50 translate-middle-x toast mb-2 w-50' data-autohide='true'><div class='toast-header bg-success' style='font-size: 20px;'><span class='mr-auto text-white'><i class='las la-check-square'></i>&nbsp;&nbsp;¡Correcto!</span></div><div class='toast-body bg-success-10 text-success text-center' style='font-size: 28px;'>El Token es correcto y fue guardado</div></div>";
$MESSAGE_TOKEN_INCORRECTO =             "<div class='bottom-0 start-50 translate-middle-x toast mb-2 w-50' data-autohide='true'><div class='toast-header bg-danger' style='font-size: 20px;'><span class='mr-auto text-white'><i class='las la-window-close'></i>&nbsp;&nbsp;¡Error!</span></div><div class='toast-body bg-danger-10 text-danger text-center' style='font-size: 28px;'>El token es incorrecto!</div></div>";
$MESSAGE_TOKEN_NO_VERIFICADO =          "<div class='bottom-0 start-50 translate-middle-x toast mb-2 w-50' data-autohide='true'><div class='toast-header bg-danger' style='font-size: 20px;'><span class='mr-auto text-white'><i class='las la-window-close'></i>&nbsp;&nbsp;¡Error!</span></div><div class='toast-body bg-danger-10 text-danger text-center' style='font-size: 28px;'>No fue posible verificar el token!</div></div>";
$MESSAGE_SIN_TOKEN =                    "<div class='bottom-0 start-50 translate-middle-x toast mb-2 w-50' data-autohide='true'><div class='toast-header bg-danger' style='font-size: 20px;'><span class='mr-auto text-white'><i class='las la-window-close'></i>&nbsp;&nbsp;¡Error!</span></div><div class='toast-body bg-danger-10 text-danger text-center' style='font-size: 28px;'>No se ha configurado el token de Telegram.</div></div>";
$MENSAJE_ANNO_FACTURA_AEROPUERTO =      "<div class='bottom-0 start-50 translate-middle-x toast mb-2 w-50' data-autohide='true'><div class='toast-header bg-danger' style='font-size: 20px;'><span class='mr-auto text-white'><i class='las la-window-close'></i>&nbsp;&nbsp;¡Error!</span></div><div class='toast-body bg-danger-10 text-danger text-center' style='font-size: 28px;'>Falta el a&ntilde;o actual delante del n&uacute;mero de Factura</div></div>";
/** FIN MENSAJES DEL SISTEMA */

/** INICIO STICKER PARA ENVIAR POR TELEGRAM */
/** LISTADO DE STICKER A UTILIZAR */
$STICKER1 = "CAACAgEAAxkBAAENa5lndWMrhNe4lpbu14dx16E5glsbmgADAwACzD8AAUalGWDY7INDGDYE";
$STICKER2 = "CAACAgEAAxkBAAENa8pndWNVJxvT-Tlj1ThRNM_LuA_9NQAC9AEAAmIhwEelF8qLGT2oyjYE";
$STICKER3 = "CAACAgEAAxkBAAENa5tndWMwsqh5uzXBO0BUqq8m7jqqZgACKgEAAvvNCEa9xza9QreuTjYE";
$STICKER4 = "CAACAgEAAxkBAAENa6FndWM3v8ie6e6CNfLnyC-3vGnK5QAChQEAAkMBCEbU7iHJREACITYE";
$STICKER5 = "CAACAgEAAxkBAAENa6JndWM4DZuIh9LDRTbs3b8SGnJdTQACswQAAnPRmUeudcKk9sAtpDYE";
$STICKER6 = "CAACAgEAAxkBAAENa6dndWM7khU0XenZIUxf351JwJ40_AACRgQAAuHI4UbQum058zxDhDYE";
$STICKER7 = "CAACAgEAAxkBAAENa71ndWNMQpkLFSahqL74hZfppvBLGgACOQQAAgyGoUdpJf2XB6AfeDYE";
$STICKER8 = "CAACAgEAAxkBAAENa8hndWNUuzov7cdvb6EVO5NnvOAScQACwAIAAuoewEe6CWO0GV8UcDYE";
$STICKER9 = "CAACAgEAAxkBAAENa-1ndWNtqSX0TuO_I3QlU4q_ZgehHQAC9wMAAjK3GEdqBKh8QnF3GzYE";
$STICKER10 = "CAACAgEAAxkBAAENa_dndWNzf5Ns-5fWoSodQYfOAAHaghUAAhIDAAJoctlE4nVEwDDPDH42BA";
$STICKER11 = "CAACAgEAAxkBAAENbBtndWOZDJRRLUi-7_C-ayDhq3Eh-AAClgMAAl5reUWf4kO1o3WlzTYE";
$STICKER12 = "CAACAgEAAxkBAAENbCFndWOj3Sc0XHPGMIPJ9MzQlToPhQACJwQAAgLvWUS3n0ESJi0P6jYE";
$STICKER13 = "CAACAgEAAxkBAAENbL1ndWavaH7Hl-oRmvyAHxRdLShZdgACCAQAAtAkmUaNrodkJghY7DYE";
$STICKER14 = "CAACAgEAAxkBAAENbCNndWOlecNwhSX6UZfFL7x3SCDj4QACwQIAAplCoUZmAAEWPhun3w42BA";
$STICKER15 = "CAACAgEAAxkBAAENbCVndWOnVwOPJR8WtEBGqlPnhumWDAACFQMAAv5NoUaoZTouVeYQODYE";
$STICKER16 = "CAACAgEAAxkBAAENbCpndWOvGGNYyFRgNaaGjFLnOvonBgACtAMAAtD6oEYBRwm9c2iG6zYE";
$STICKER17 = "CAACAgEAAxkBAAENbCtndWOwou2rfTUWiybkDPlZo5pphwAC2QMAAq4dwUVJYLIToO1M3DYE";
$STICKER18 = "CAACAgEAAxkBAAENbDVndWO4ufRY1QlTZfQcyIf2N53JYgACsQUAAnBvwUWEOoWlxQ1AvTYE";
$STICKER19 = "CAACAgEAAxkBAAENbC9ndWOzLHm8OgABxaYempbA3i8OQR4AAmYFAALDscFFrn6kK2wxx0Q2BA";
$STICKER20 = "CAACAgEAAxkBAAENbO1ndWbsgAABOBPdtr_QU1-9gMew88AAAtgEAAIa5PBE8NR1FMoQOlo2BA";
$STICKER21 = "CAACAgEAAxkBAAENbP9ndWcDDlj37cVs0iNAWxOVKu3J8gACwQcAAjIk-EVzIIaeqHOz_zYE";

/** CREANDO UN ARRAY CON LOS STICKER A UTILIZAR */
$STICKERS = array($STICKER1, $STICKER2, $STICKER3, $STICKER4, $STICKER5, $STICKER6, $STICKER7, $STICKER8, $STICKER9, $STICKER10, $STICKER11, $STICKER12, $STICKER13, $STICKER14, $STICKER15, $STICKER16, $STICKER17, $STICKER18, $STICKER19, $STICKER20, $STICKER21);
/** FIN STICKER PARA ENVIAR POR TELEGRAM */